
export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const FETCH_REPOS_PENDING = 'FETCH_REPOS_PENDING';
export const FETCH_REPOS_SUCCESS = 'FETCH_REPOS_SUCCESS';
export const FETCH_REPOS_ERROR = 'FETCH_REPOS_ERROR';
export const SEARCH_FIELD_FOCUS = 'SEARCH_FIELD_FOCUS';
export const SEARCH_FIELD_BLUR = 'SEARCH_FIELD_BLUR';
